// zephyr/src/tls/tls_creds.cpp
// Common TLS credential store for HDV-Sim firmware.
//
// Loads the self-signed RSA-2048 server certificate and private key (generated
// by scripts/gen_tls_certs.sh and embedded at build time as .inc files) into
// the Zephyr TLS credential store under HDV_TLS_SERVER_TAG.
//
// Call tls_creds_init() once before creating any TLS socket.  The credentials
// are then available to all sockets in the process — HTTPS server and future
// MQTTS client both use the same tag.

#include <zephyr/kernel.h>          // must precede tls_credentials.h — provides size_t
#include <zephyr/net/tls_credentials.h>
#include <zephyr/logging/log.h>

#include "tls_creds.hpp"

LOG_MODULE_DECLARE(hdv_sim, LOG_LEVEL_INF);

// server_cert.inc and server_key.inc are generated by generate_inc_file_for_target()
// in CMakeLists.txt from zephyr/certs/server.crt and zephyr/certs/server.key.
// They contain a comma-separated list of hex byte literals (no length variable).
//
// IMPORTANT: file2hex.py does NOT append a null terminator. mbedTLS PEM parser
// checks buf[buflen-1] == '\0' to detect PEM format — missing '\0' causes it
// to fall through to DER parsing, which fails on PEM data.  The ', '\0'' below
// fixes this; sizeof() counts it, so tls_credential_add gets the correct length.
static const unsigned char server_cert[] = {
#include "server_cert.inc"
, '\0'  // required: mbedTLS PEM parser needs null-terminated string
};
static const unsigned char server_key[] = {
#include "server_key.inc"
, '\0'  // required: mbedTLS PEM parser needs null-terminated string
};

int tls_creds_init(void)
{
    int rc;

    rc = tls_credential_add(HDV_TLS_SERVER_TAG,
                            TLS_CREDENTIAL_SERVER_CERTIFICATE,
                            server_cert, sizeof(server_cert));
    if (rc == -EEXIST) {
        // Already loaded (e.g. called twice) — not an error.
        LOG_DBG("TLS: credentials already registered (tag %d)", HDV_TLS_SERVER_TAG);
        return 0;
    }
    if (rc < 0) {
        LOG_ERR("TLS: cert registration failed (rc=%d)", rc);
        return rc;
    }

    rc = tls_credential_add(HDV_TLS_SERVER_TAG,
                            TLS_CREDENTIAL_PRIVATE_KEY,
                            server_key, sizeof(server_key));
    if (rc < 0) {
        LOG_ERR("TLS: key registration failed (rc=%d)", rc);
        return rc;
    }

    LOG_INF("TLS: credentials loaded — tag %d, cert %zu B, key %zu B",
            HDV_TLS_SERVER_TAG, sizeof(server_cert), sizeof(server_key));
    return 0;
}
