// zephyr/src/http/http_server.cpp
// HTTPS server thread — TLS socket lifecycle + request routing.
//
// Routes:
//   GET  /            → login page
//   GET  /login       → login page
//   POST /login       → validate token → set session cookie → redirect /dash
//   GET  /dash        → dashboard (requires session cookie or Bearer token)
//   GET  /dash?...    → apply command + dashboard (requires auth)
//   GET  /logout      → invalidate session + redirect /
//   other             → redirect /
//
// Security:
//   - TLS 1.2, self-signed RSA-2048 cert (scripts/gen_http_token.sh)
//   - Bearer token OR browser session cookie required for /dash
//   - Input values clamped in apply_web_cmd() before writing to g_cmd

#include <zephyr/kernel.h>
#include <zephyr/net/socket.h>
#include <zephyr/net/tls_credentials.h>
#include <zephyr/net/net_ip.h>
#include <zephyr/logging/log.h>
#include <string.h>
#include <stdio.h>   /* snprintf */

#include "http_internal.hpp"

LOG_MODULE_DECLARE(hdv_sim, LOG_LEVEL_INF);

// ── Embedded TLS credentials ──────────────────────────────────────────────────
// Generated by scripts/gen_http_token.sh → placed in zephyr/certs/
// Compiled via generate_inc_file_for_target() in CMakeLists.txt.
// generate_inc_file_for_target emits a trailing comma; null terminator placed
// directly (no leading comma) to avoid double-comma syntax error.
static const unsigned char server_cert[] = {
#include "server_cert.inc"
0x00
};
static const unsigned char server_key[] = {
#include "server_key.inc"
0x00
};

#define TLS_TAG 1

// ── Response helpers ──────────────────────────────────────────────────────────

void send_401(int fd)
{
    static const char resp[] =
        "HTTP/1.1 401 Unauthorized\r\n"
        "Content-Type: text/plain\r\n"
        "Content-Length: 13\r\n"
        "Connection: close\r\n"
        "\r\n"
        "Unauthorized\n";
    zsock_send(fd, resp, sizeof(resp) - 1, 0);
}

static void send_redirect(int fd, const char* location)
{
    char buf[256];
    int n = snprintf(buf, sizeof(buf),
        "HTTP/1.1 302 Found\r\n"
        "Location: %s\r\n"
        "Connection: close\r\n"
        "Content-Length: 0\r\n"
        "\r\n",
        location);
    zsock_send(fd, buf, n, 0);
}

// Redirect to /dash after successful login; set session cookie.
static void send_login_success(int fd, const char* sid)
{
    char buf[384];
    int n = snprintf(buf, sizeof(buf),
        "HTTP/1.1 302 Found\r\n"
        "Location: /dash\r\n"
        "Set-Cookie: sid=%s; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=3600\r\n"
        "Connection: close\r\n"
        "Content-Length: 0\r\n"
        "\r\n",
        sid);
    zsock_send(fd, buf, n, 0);
}

// Clear session cookie on logout.
static void send_logout_redirect(int fd)
{
    static const char resp[] =
        "HTTP/1.1 302 Found\r\n"
        "Location: /\r\n"
        "Set-Cookie: sid=; Path=/; Secure; HttpOnly; Max-Age=0\r\n"
        "Connection: close\r\n"
        "Content-Length: 0\r\n"
        "\r\n";
    zsock_send(fd, resp, sizeof(resp) - 1, 0);
}

// ── HTTPS server thread ───────────────────────────────────────────────────────
static void http_server_thread(void*, void*, void*)
{
    k_msleep(3000);  // let Ethernet settle before TLS init

    int rc;
    rc = tls_credential_add(TLS_TAG, TLS_CREDENTIAL_SERVER_CERTIFICATE,
                             server_cert, sizeof(server_cert));
    if (rc < 0) { LOG_ERR("HTTPS: cert add failed: %d", rc); return; }

    rc = tls_credential_add(TLS_TAG, TLS_CREDENTIAL_PRIVATE_KEY,
                             server_key, sizeof(server_key));
    if (rc < 0) { LOG_ERR("HTTPS: key add failed: %d", rc); return; }

    int srv = zsock_socket(AF_INET, SOCK_STREAM, IPPROTO_TLS_1_2);
    if (srv < 0) { LOG_ERR("HTTPS: socket() failed: %d", srv); return; }

    sec_tag_t sec_tag = TLS_TAG;
    rc = zsock_setsockopt(srv, SOL_TLS, TLS_SEC_TAG_LIST, &sec_tag, sizeof(sec_tag));
    if (rc < 0) { LOG_ERR("HTTPS: TLS_SEC_TAG_LIST failed: %d", rc); zsock_close(srv); return; }

    // TCP TLS server role is implicit from listen(); TLS_ROLE is DTLS-only.
    // Disable peer certificate verification — auth is via Bearer/session.
    int peer_verify = TLS_PEER_VERIFY_NONE;
    rc = zsock_setsockopt(srv, SOL_TLS, TLS_PEER_VERIFY, &peer_verify, sizeof(peer_verify));
    if (rc < 0) { LOG_ERR("HTTPS: TLS_PEER_VERIFY failed: %d", rc); zsock_close(srv); return; }

    int opt = 1;
    zsock_setsockopt(srv, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    struct sockaddr_in addr{};
    addr.sin_family      = AF_INET;
    addr.sin_port        = htons(443);
    addr.sin_addr.s_addr = INADDR_ANY;

    if (zsock_bind(srv, (struct sockaddr*)&addr, sizeof(addr)) < 0) {
        LOG_ERR("HTTPS: bind() failed"); zsock_close(srv); return;
    }
    if (zsock_listen(srv, 3) < 0) {
        LOG_ERR("HTTPS: listen() failed"); zsock_close(srv); return;
    }

    LOG_INF("HTTPS server listening on 192.168.1.80:443 (TLS 1.2)");

    while (true) {
        struct sockaddr_in client_addr{};
        socklen_t client_len = sizeof(client_addr);
        int client = zsock_accept(srv, (struct sockaddr*)&client_addr, &client_len);
        if (client < 0) { k_msleep(10); continue; }

        // ── Parse request ─────────────────────────────────────────────────────
        char method[8]   = {};
        char path[64]    = {};
        char query[128]  = {};
        char auth[128]   = {};
        char cookie[256] = {};
        int  clen        = 0;

        read_request_line(client,
                          method, sizeof(method),
                          path,   sizeof(path),
                          query,  sizeof(query));
        read_headers(client,
                     auth,   sizeof(auth),
                     cookie, sizeof(cookie),
                     &clen);

        bool is_get    = (method[0] == 'G');
        bool is_post   = (method[0] == 'P');
        bool is_root   = (path[0] == '\0' || strcmp(path, "/") == 0);
        bool is_login  = (strcmp(path, "/login")  == 0);
        bool is_dash   = (strcmp(path, "/dash")   == 0);
        bool is_logout = (strcmp(path, "/logout") == 0);

        bool has_bearer  = verify_bearer(auth);
        bool has_session = session_check(cookie);
        bool authed      = has_bearer || has_session;

        // ── Route ─────────────────────────────────────────────────────────────

        if (is_post && is_login) {
            // Read POST body (token=<hex>)
            char body[192] = {};
            int to_read = (clen > 0 && clen < (int)sizeof(body) - 1) ? clen : 0;
            int got = 0;
            while (got < to_read) {
                int r = zsock_recv(client, body + got, to_read - got, 0);
                if (r <= 0) break;
                got += r;
            }

            // Extract token value from "token=<value>"
            const char* tok = "";
            const char* eq  = strstr(body, "token=");
            if (eq) tok = eq + 6;
            // Strip trailing '&' or whitespace
            char tok_clean[128] = {};
            int  ti = 0;
            while (tok[ti] && tok[ti] != '&' && tok[ti] != '\r' && tok[ti] != '\n'
                   && ti < (int)sizeof(tok_clean) - 1)
                tok_clean[ti] = tok[ti++];
            tok_clean[ti] = '\0';

            if (verify_bearer(tok_clean)) {
                char sid[33] = {};
                session_create(sid, sizeof(sid));
                LOG_INF("HTTPS: login OK → /dash");
                send_login_success(client, sid);
            } else {
                LOG_WRN("HTTPS: login FAILED — bad token");
                send_login_page(client, true);
            }

        } else if (is_get && is_logout) {
            session_invalidate(cookie);
            LOG_INF("HTTPS: logout");
            send_logout_redirect(client);

        } else if (is_get && (is_root || is_login)) {
            send_login_page(client, false);

        } else if (is_get && is_dash) {
            if (authed) {
                if (query[0]) apply_web_cmd(query);
                send_page(client);
            } else {
                LOG_WRN("HTTPS: /dash — no valid session/token → redirect login");
                send_redirect(client, "/");
            }

        } else if (is_get && authed) {
            // Unknown authenticated path → redirect to dashboard
            send_redirect(client, "/dash");

        } else {
            send_redirect(client, "/");
        }

        zsock_close(client);
    }
}

// Stack 24 KB — ECDHE-RSA TLS handshake needs ~10-15 KB on top of locals
K_THREAD_DEFINE(http_tid, 24576, http_server_thread, NULL, NULL, NULL, 10, 0, 0);
