// zephyr/src/http/http_cmd.cpp
// HTTPS request parsing, Bearer token authentication, and actuator command injection.
//
// Security:
//   - Every API request must include: Authorization: Bearer <token>
//   - Browser sessions are managed by http_session.cpp (cookie-based)
//   - Token is defined in http_auth.hpp (generated by scripts/gen_http_token.sh)
//   - Input values are clamped to physical limits before writing to g_cmd

#include <zephyr/kernel.h>
#include <zephyr/net/socket.h>
#include <zephyr/logging/log.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>  /* strncasecmp */

#include "sim/actuator_cmd.hpp"
#include "http_auth.hpp"   // HDV_API_TOKEN (generated, gitignored)

LOG_MODULE_DECLARE(hdv_sim, LOG_LEVEL_INF);

extern sim::ActuatorCmd g_cmd;
extern struct k_mutex   g_cmd_mutex;

// ── Helpers ───────────────────────────────────────────────────────────────────

static inline double clamp_d(double v, double lo, double hi) {
    return v < lo ? lo : (v > hi ? hi : v);
}

static const char* find_param(const char* qs, const char* key)
{
    int klen = (int)strlen(key);
    const char* p = qs;
    while (*p) {
        if (strncmp(p, key, klen) == 0 && p[klen] == '=')
            return p + klen + 1;
        while (*p && *p != '&') ++p;
        if (*p == '&') ++p;
    }
    return nullptr;
}

// ── Request line reader ───────────────────────────────────────────────────────
// Reads the first HTTP line and fills method, path, and query separately.
// Example line: "GET /dash?steer=5&torque=0 HTTP/1.1\r\n"
void read_request_line(int fd,
                       char* method_out, int mlen,
                       char* path_out,   int plen,
                       char* query_out,  int qlen)
{
    method_out[0] = path_out[0] = query_out[0] = '\0';

    char line[256];
    int  li = 0;
    while (li < (int)sizeof(line) - 1) {
        char c;
        if (zsock_recv(fd, &c, 1, 0) <= 0) break;
        if (c == '\n') break;
        line[li++] = c;
    }
    // Strip trailing \r
    if (li > 0 && line[li-1] == '\r') li--;
    line[li] = '\0';

    // Parse "METHOD /path?query HTTP/x.x"
    char* p = line;

    // Method
    int i = 0;
    while (*p && *p != ' ' && i < mlen - 1) method_out[i++] = *p++;
    method_out[i] = '\0';
    while (*p == ' ') ++p;

    // Path
    i = 0;
    while (*p && *p != '?' && *p != ' ' && i < plen - 1) path_out[i++] = *p++;
    path_out[i] = '\0';

    // Query (after '?', before ' ')
    if (*p == '?') {
        ++p;
        i = 0;
        while (*p && *p != ' ' && i < qlen - 1) query_out[i++] = *p++;
        query_out[i] = '\0';
    }
}

// ── Header reader ─────────────────────────────────────────────────────────────
// Drains all headers; captures Authorization Bearer value, Cookie header,
// and Content-Length.
void read_headers(int fd,
                  char* auth_out,   int alen,
                  char* cookie_out, int clen,
                  int*  content_len)
{
    auth_out[0] = cookie_out[0] = '\0';
    *content_len = 0;

    char line[256];
    int  li = 0;

    while (true) {
        char c;
        if (zsock_recv(fd, &c, 1, 0) <= 0) break;

        if (c == '\n') {
            if (li > 0 && line[li-1] == '\r') li--;
            line[li] = '\0';

            if (li == 0) break;  // blank line = end of headers

            if (strncasecmp(line, "Authorization:", 14) == 0) {
                const char* val = line + 14;
                while (*val == ' ') ++val;
                if (strncmp(val, "Bearer ", 7) == 0) {
                    strncpy(auth_out, val + 7, alen - 1);
                    auth_out[alen-1] = '\0';
                }
            } else if (strncasecmp(line, "Cookie:", 7) == 0) {
                const char* val = line + 7;
                while (*val == ' ') ++val;
                strncpy(cookie_out, val, clen - 1);
                cookie_out[clen-1] = '\0';
            } else if (strncasecmp(line, "Content-Length:", 15) == 0) {
                *content_len = (int)atoi(line + 15);
            }

            li = 0;
        } else if (li < (int)sizeof(line) - 1) {
            line[li++] = c;
        }
    }
}

// ── Bearer token verification ─────────────────────────────────────────────────
bool verify_bearer(const char* token_value)
{
    if (!token_value || !token_value[0]) return false;
    size_t expected_len = strlen(HDV_API_TOKEN);
    if (strlen(token_value) != expected_len) return false;
    return strncmp(token_value, HDV_API_TOKEN, expected_len) == 0;
}

// ── Command application ───────────────────────────────────────────────────────
// Caller must have already verified auth (session or Bearer token).
void apply_web_cmd(const char* qs)
{
    sim::ActuatorCmd cmd;
    k_mutex_lock(&g_cmd_mutex, K_FOREVER);
    cmd = g_cmd;
    k_mutex_unlock(&g_cmd_mutex);

    const char* v;
    if ((v = find_param(qs, "steer")))
        cmd.steer_cmd_deg       = clamp_d(atof(v), -45.0, 45.0);
    if ((v = find_param(qs, "torque")))
        cmd.drive_torque_cmd_nm = clamp_d(atof(v), 0.0, 145000.0);
    if ((v = find_param(qs, "brake")))
        cmd.brake_cmd_pct       = clamp_d(atof(v), 0.0, 100.0);
    if ((v = find_param(qs, "gear"))) {
        cmd.gear_position = (v[0] == 'F') ? sim::GearPosition::FORWARD :
                            (v[0] == 'R') ? sim::GearPosition::REVERSE :
                                            sim::GearPosition::NEUTRAL;
    }
    if ((v = find_param(qs, "enable"))) cmd.system_enable = (v[0] == '1');

    cmd.last_update_t_s = (double)k_uptime_get_32() / 1000.0;

    k_mutex_lock(&g_cmd_mutex, K_FOREVER);
    g_cmd = cmd;
    k_mutex_unlock(&g_cmd_mutex);
}
