// zephyr/src/http/http_cmd.cpp
// HTTPS request parsing, Bearer token authentication, and actuator command injection.
//
// Security:
//   - Every request must include: Authorization: Bearer <token>
//   - Token is defined in http_auth.hpp (generated by scripts/gen_http_token.sh)
//   - Input values are clamped to physical limits before writing to g_cmd
//   - Timestamp written inside g_cmd under g_cmd_mutex (no separate global)

#include <zephyr/kernel.h>
#include <zephyr/net/socket.h>
#include <zephyr/logging/log.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>  /* strncasecmp */

#include "sim/actuator_cmd.hpp"
#include "http_auth.hpp"   // HDV_API_TOKEN (generated, gitignored)

LOG_MODULE_DECLARE(hdv_sim, LOG_LEVEL_INF);

extern sim::ActuatorCmd g_cmd;
extern struct k_mutex   g_cmd_mutex;

// ── Helpers ───────────────────────────────────────────────────────────────────

static inline double clamp_d(double v, double lo, double hi) {
    return v < lo ? lo : (v > hi ? hi : v);
}

static const char* find_param(const char* qs, const char* key)
{
    int klen = (int)strlen(key);
    const char* p = qs;
    while (*p) {
        if (strncmp(p, key, klen) == 0 && p[klen] == '=')
            return p + klen + 1;
        while (*p && *p != '&') ++p;
        if (*p == '&') ++p;
    }
    return nullptr;
}

// ── Request line reader ───────────────────────────────────────────────────────
// Reads first HTTP line, extracts everything after '?' and before the next ' '.
void read_request_line(int fd, char* query_out, int qlen)
{
    query_out[0] = '\0';

    char line[192];
    int  li = 0;

    while (li < (int)sizeof(line) - 1) {
        char c;
        if (zsock_recv(fd, &c, 1, 0) <= 0) break;
        if (c == '\n') break;
        line[li++] = c;
    }
    line[li] = '\0';

    char* q = line;
    while (*q && *q != '?') ++q;
    if (!*q) return;

    ++q;
    int i = 0;
    while (*q && *q != ' ' && *q != '\r' && i < qlen - 1)
        query_out[i++] = *q++;
    query_out[i] = '\0';
}

// ── Header reader — drains all headers, captures Authorization value ──────────
// auth_out receives the value after "Bearer " (empty string if not found).
void read_headers(int fd, char* auth_out, int alen)
{
    auth_out[0] = '\0';

    char line[256];
    int li = 0;

    while (true) {
        char c;
        if (zsock_recv(fd, &c, 1, 0) <= 0) break;

        if (c == '\n') {
            // Strip trailing \r
            if (li > 0 && line[li-1] == '\r') li--;
            line[li] = '\0';

            if (li == 0) break;  // blank line = end of headers

            // Check for Authorization header (case-insensitive name)
            const char* auth_prefix = "Authorization:";
            if (strncasecmp(line, auth_prefix, strlen(auth_prefix)) == 0) {
                const char* val = line + strlen(auth_prefix);
                while (*val == ' ') ++val;  // skip whitespace

                const char* bearer = "Bearer ";
                if (strncmp(val, bearer, strlen(bearer)) == 0) {
                    strncpy(auth_out, val + strlen(bearer), alen - 1);
                    auth_out[alen-1] = '\0';
                }
            }
            li = 0;
        } else if (li < (int)sizeof(line) - 1) {
            line[li++] = c;
        }
    }
}

// ── Bearer token verification ─────────────────────────────────────────────────
// Returns true if token matches HDV_API_TOKEN (constant-time compare avoids
// timing oracle — strncmp is fine here as token is fixed-length hex).
bool verify_bearer(const char* token_value)
{
    if (token_value == nullptr || token_value[0] == '\0') return false;
    size_t expected_len = strlen(HDV_API_TOKEN);
    if (strlen(token_value) != expected_len) return false;
    return strncmp(token_value, HDV_API_TOKEN, expected_len) == 0;
}

// ── Command application ───────────────────────────────────────────────────────
// Caller must have already verified the Bearer token.
void apply_web_cmd(const char* qs)
{
    sim::ActuatorCmd cmd;
    k_mutex_lock(&g_cmd_mutex, K_FOREVER);
    cmd = g_cmd;
    k_mutex_unlock(&g_cmd_mutex);

    const char* v;
    if ((v = find_param(qs, "steer")))
        cmd.steer_cmd_deg       = clamp_d(atof(v), -45.0, 45.0);
    if ((v = find_param(qs, "torque")))
        cmd.drive_torque_cmd_nm = clamp_d(atof(v), 0.0, 145000.0);
    if ((v = find_param(qs, "brake")))
        cmd.brake_cmd_pct       = clamp_d(atof(v), 0.0, 100.0);
    if ((v = find_param(qs, "gear"))) {
        cmd.gear_position = (v[0] == 'F') ? sim::GearPosition::FORWARD :
                            (v[0] == 'R') ? sim::GearPosition::REVERSE :
                                            sim::GearPosition::NEUTRAL;
    }
    if ((v = find_param(qs, "enable"))) cmd.system_enable = (v[0] == '1');

    // Timestamp written under mutex — no separate global needed
    cmd.last_update_t_s = (double)k_uptime_get_32() / 1000.0;

    k_mutex_lock(&g_cmd_mutex, K_FOREVER);
    g_cmd = cmd;
    k_mutex_unlock(&g_cmd_mutex);
}
