// zephyr/src/http/http_server.cpp
// HTTPS server thread — TLS socket lifecycle (open / bind / listen / accept).
// Delegates request parsing and auth to http_cmd.cpp.
// Delegates page rendering to http_page.cpp.
//
// Security:
//   - TLS 1.2 with self-signed RSA-2048 cert (generated by scripts/gen_http_token.sh)
//   - Bearer token required for every request (checked by verify_bearer())
//   - Input values clamped in apply_web_cmd() before writing to g_cmd
//
// Priority 10: below plant sim (prio 5), above LED (prio 12) and shell (prio 14).

#include <zephyr/kernel.h>
#include <zephyr/net/socket.h>
#include <zephyr/net/tls_credentials.h>
#include <zephyr/net/net_ip.h>
#include <zephyr/logging/log.h>

#include "http_internal.hpp"

LOG_MODULE_DECLARE(hdv_sim, LOG_LEVEL_INF);

// ── Embedded TLS credentials ──────────────────────────────────────────────────
// Generated by scripts/gen_http_token.sh → placed in zephyr/certs/
// Compiled via generate_inc_file_for_target() in CMakeLists.txt.
// A null byte is appended after the .inc content — required for PEM format.
// Note: generate_inc_file_for_target emits a trailing comma, so we place
// the null terminator directly (no leading comma) to avoid ,,0 syntax errors.
static const unsigned char server_cert[] = {
#include "server_cert.inc"
0x00
};
static const unsigned char server_key[] = {
#include "server_key.inc"
0x00
};

#define TLS_TAG 1

// ── HTTP 401 response ─────────────────────────────────────────────────────────
void send_401(int fd)
{
    static const char resp[] =
        "HTTP/1.1 401 Unauthorized\r\n"
        "Content-Type: text/plain\r\n"
        "Content-Length: 13\r\n"
        "Connection: close\r\n"
        "\r\n"
        "Unauthorized\n";
    zsock_send(fd, resp, sizeof(resp) - 1, 0);
}

// ── HTTPS server thread ───────────────────────────────────────────────────────
static void http_server_thread(void*, void*, void*)
{
    k_msleep(3000);  // extra delay to let Ethernet settle before TLS init

    // Register TLS credentials (cert + private key)
    int rc;
    rc = tls_credential_add(TLS_TAG, TLS_CREDENTIAL_SERVER_CERTIFICATE,
                             server_cert, sizeof(server_cert));
    if (rc < 0) {
        LOG_ERR("HTTPS: tls_credential_add(cert) failed: %d", rc);
        return;
    }
    rc = tls_credential_add(TLS_TAG, TLS_CREDENTIAL_PRIVATE_KEY,
                             server_key, sizeof(server_key));
    if (rc < 0) {
        LOG_ERR("HTTPS: tls_credential_add(key) failed: %d", rc);
        return;
    }

    // Create TLS server socket
    int srv = zsock_socket(AF_INET, SOCK_STREAM, IPPROTO_TLS_1_2);
    if (srv < 0) {
        LOG_ERR("HTTPS: socket() failed: %d", srv);
        return;
    }

    // Bind TLS credentials to socket
    sec_tag_t sec_tag = TLS_TAG;
    rc = zsock_setsockopt(srv, SOL_TLS, TLS_SEC_TAG_LIST, &sec_tag, sizeof(sec_tag));
    if (rc < 0) {
        LOG_ERR("HTTPS: TLS_SEC_TAG_LIST failed: %d", rc);
        zsock_close(srv);
        return;
    }

    // TLS_ROLE is DTLS-only in Zephyr; for TCP TLS the server role is
    // implicit once listen() is called on a TLS socket.
    // Disable peer (client) certificate verification — we use Bearer token auth.
    int peer_verify = TLS_PEER_VERIFY_NONE;
    rc = zsock_setsockopt(srv, SOL_TLS, TLS_PEER_VERIFY, &peer_verify, sizeof(peer_verify));
    if (rc < 0) {
        LOG_ERR("HTTPS: TLS_PEER_VERIFY failed: %d", rc);
        zsock_close(srv);
        return;
    }

    int opt = 1;
    zsock_setsockopt(srv, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    struct sockaddr_in addr{};
    addr.sin_family      = AF_INET;
    addr.sin_port        = htons(443);
    addr.sin_addr.s_addr = INADDR_ANY;

    if (zsock_bind(srv, (struct sockaddr*)&addr, sizeof(addr)) < 0) {
        LOG_ERR("HTTPS: bind() failed");
        zsock_close(srv);
        return;
    }

    if (zsock_listen(srv, 3) < 0) {
        LOG_ERR("HTTPS: listen() failed");
        zsock_close(srv);
        return;
    }

    LOG_INF("HTTPS server listening on 192.168.1.80:443 (TLS 1.2)");

    while (true) {
        struct sockaddr_in client_addr{};
        socklen_t client_len = sizeof(client_addr);
        int client = zsock_accept(srv, (struct sockaddr*)&client_addr, &client_len);
        if (client < 0) {
            k_msleep(10);
            continue;
        }

        char query[128] = {};
        char auth[128]  = {};

        read_request_line(client, query, sizeof(query));
        read_headers(client, auth, sizeof(auth));

        if (!verify_bearer(auth)) {
            LOG_WRN("HTTPS: 401 — invalid or missing Bearer token");
            send_401(client);
            zsock_close(client);
            continue;
        }

        if (query[0] != '\0') {
            apply_web_cmd(query);
        }

        send_page(client);
        zsock_close(client);
    }
}

// Stack increased to 12 KB for TLS handshake overhead
K_THREAD_DEFINE(http_tid, 12288, http_server_thread, NULL, NULL, NULL, 10, 0, 0);
