// AUTO-GENERATED by tools/gen_can_map.py — DO NOT EDIT MANUALLY
// Source: config/can_map.dbc
// Re-generate: python3 tools/gen_can_map.py
//
// 1 RX frame(s), 15 TX frame(s), 65 signals total
#pragma once
#include <stdint.h>
#include <stdbool.h>

namespace can_static {

// Signal descriptor — all data lives in flash (constexpr/const).
struct SigDef {
    const char* name;
    int16_t     start_bit;
    uint8_t     bit_len;
    bool        little_endian;  // true=Intel (@1), false=Motorola (@0)
    bool        is_signed;
    float       factor;
    float       offset;
};

// Frame descriptor.
struct FrameDef {
    uint32_t        id;          // 29-bit J1939 identifier (no EFF flag)
    bool            is_extended; // always true for J1939
    bool            is_rx;       // true = we receive this frame
    uint16_t        cycle_ms;    // nominal TX period (0 = event-driven)
    uint8_t         dlc;
    const char*     name;
    const SigDef*   sigs;
    uint8_t         sig_count;
};

// ── Signal arrays (one per frame, stored in flash) ─────────────────────────────────────

static const SigDef k_sigs_actuator_cmd_1[] = {
    { "system_enable", 0, 1, true, false, 1.0f, 0.0f },
    { "gear_position", 1, 2, true, false, 1.0f, 0.0f },
    { "mode", 3, 2, true, false, 1.0f, 0.0f },
    { "steer_cmd_deg", 8, 16, true, true, 0.1f, 0.0f },
    { "drive_torque_cmd_nm", 24, 16, true, true, 10.0f, 0.0f },
    { "brake_cmd_pct", 40, 8, true, false, 1.0f, 0.0f },
};

static const SigDef k_sigs_imu_acc[] = {
    { "imu_ax_mps2", 0, 16, true, true, 0.01f, 0.0f },
    { "imu_ay_mps2", 16, 16, true, true, 0.01f, 0.0f },
    { "imu_az_mps2", 32, 16, true, true, 0.01f, 0.0f },
    { "imu_temp_c", 48, 16, true, true, 0.01f, 0.0f },
};

static const SigDef k_sigs_imu_gyr[] = {
    { "imu_gx_rps", 0, 16, true, true, 0.001f, 0.0f },
    { "imu_gy_rps", 16, 16, true, true, 0.001f, 0.0f },
    { "imu_gz_rps", 32, 16, true, true, 0.001f, 0.0f },
    { "imu_status", 48, 8, true, false, 1.0f, 0.0f },
};

static const SigDef k_sigs_gnss_ll[] = {
    { "gnss_lat_deg", 0, 32, true, true, 1e-07f, 0.0f },
    { "gnss_lon_deg", 32, 32, true, true, 1e-07f, 0.0f },
};

static const SigDef k_sigs_gnss_av[] = {
    { "gnss_alt_m", 0, 16, true, true, 0.1f, -1000.0f },
    { "gnss_vn_mps", 16, 16, true, true, 0.01f, 0.0f },
    { "gnss_ve_mps", 32, 16, true, true, 0.01f, 0.0f },
    { "gnss_fix_type", 48, 8, true, false, 1.0f, 0.0f },
    { "gnss_sat_count", 56, 8, true, false, 1.0f, 0.0f },
};

static const SigDef k_sigs_wheels_1[] = {
    { "wheel_fl_rps", 0, 16, true, true, 0.01f, 0.0f },
    { "wheel_fr_rps", 16, 16, true, true, 0.01f, 0.0f },
    { "wheel_rl_rps", 32, 16, true, true, 0.01f, 0.0f },
    { "wheel_rr_rps", 48, 16, true, true, 0.01f, 0.0f },
};

static const SigDef k_sigs_steer_state[] = {
    { "steer_deg", 0, 16, true, true, 0.1f, 0.0f },
    { "steer_rate_dps", 16, 16, true, true, 0.1f, 0.0f },
    { "delta_fl_deg", 32, 12, true, true, 0.1f, 0.0f },
    { "delta_fr_deg", 44, 12, true, true, 0.1f, 0.0f },
    { "steer_fault", 56, 8, true, false, 1.0f, 0.0f },
};

static const SigDef k_sigs_batt_state[] = {
    { "batt_v", 0, 16, true, false, 0.1f, 0.0f },
    { "batt_i", 16, 16, true, true, 0.1f, 0.0f },
    { "batt_soc_pct", 32, 8, true, false, 0.5f, 0.0f },
    { "batt_temp_c", 40, 8, true, false, 1.0f, -40.0f },
    { "batt_power_kw", 48, 16, true, true, 0.1f, 0.0f },
};

static const SigDef k_sigs_radar_1[] = {
    { "radar_target_range_m", 0, 16, true, false, 0.1f, 0.0f },
    { "radar_target_rel_vel_mps", 16, 16, true, true, 0.01f, 0.0f },
    { "radar_target_angle_deg", 32, 16, true, true, 0.1f, 0.0f },
    { "radar_status", 48, 8, true, false, 1.0f, 0.0f },
};

static const SigDef k_sigs_vehicle_state_1[] = {
    { "vehicle_speed_mps", 0, 16, true, true, 0.01f, 0.0f },
    { "vehicle_accel_mps2", 16, 16, true, true, 0.01f, 0.0f },
    { "yaw_rate_radps", 32, 16, true, true, 0.0001f, 0.0f },
    { "status_flags", 48, 8, true, false, 1.0f, 0.0f },
};

static const SigDef k_sigs_motor_state_1[] = {
    { "motor_torque_nm", 0, 16, true, true, 10.0f, 0.0f },
    { "motor_power_kw", 16, 16, true, true, 0.1f, 0.0f },
    { "motor_speed_rpm", 32, 16, true, false, 1.0f, 0.0f },
    { "motor_temp_c", 48, 8, true, false, 1.0f, -40.0f },
};

static const SigDef k_sigs_brake_state[] = {
    { "brake_force_kn", 0, 16, true, false, 0.01f, 0.0f },
    { "brake_pct_actual", 16, 8, true, false, 0.5f, 0.0f },
    { "regen_power_kw", 24, 16, true, false, 0.1f, 0.0f },
    { "brake_temp_c", 40, 8, true, false, 1.0f, -40.0f },
};

static const SigDef k_sigs_position_state[] = {
    { "pos_x_m", 0, 32, true, true, 0.01f, 0.0f },
    { "pos_y_m", 32, 32, true, true, 0.01f, 0.0f },
};

static const SigDef k_sigs_orientation_state[] = {
    { "yaw_deg", 0, 16, true, true, 0.01f, 0.0f },
    { "yaw_rad", 16, 16, true, true, 0.001f, 0.0f },
    { "yaw_rate_dps", 32, 16, true, true, 0.1f, 0.0f },
};

static const SigDef k_sigs_drivetrain_state[] = {
    { "gear_ratio", 0, 16, true, false, 0.01f, 0.0f },
    { "drivetrain_eff_pct", 16, 8, true, false, 0.5f, 0.0f },
    { "wheel_radius_mm", 24, 16, true, false, 1.0f, 0.0f },
    { "wheelbase_mm", 40, 16, true, false, 1.0f, 0.0f },
    { "track_width_mm", 56, 8, true, false, 100.0f, 0.0f },
};

static const SigDef k_sigs_diagnostic_state[] = {
    { "sim_time_s", 0, 32, true, false, 0.001f, 0.0f },
    { "loop_time_us", 32, 16, true, false, 1.0f, 0.0f },
    { "error_count", 48, 8, true, false, 1.0f, 0.0f },
    { "status", 56, 8, true, false, 1.0f, 0.0f },
};

// ── Frame table ─────────────────────────────────────────────────────────

static const FrameDef k_frames[16] = {
    // ACTUATOR_CMD_1  (0x98EFF021)
    { 0x98EFF021u, true, true, 10u, 8u,
      "ACTUATOR_CMD_1",
      k_sigs_actuator_cmd_1, static_cast<uint8_t>(sizeof(k_sigs_actuator_cmd_1) / sizeof(k_sigs_actuator_cmd_1[0])) },
    // IMU_ACC  (0x8CFF0028)
    { 0x8CFF0028u, true, false, 5u, 8u,
      "IMU_ACC",
      k_sigs_imu_acc, static_cast<uint8_t>(sizeof(k_sigs_imu_acc) / sizeof(k_sigs_imu_acc[0])) },
    // IMU_GYR  (0x8CFF0128)
    { 0x8CFF0128u, true, false, 5u, 8u,
      "IMU_GYR",
      k_sigs_imu_gyr, static_cast<uint8_t>(sizeof(k_sigs_imu_gyr) / sizeof(k_sigs_imu_gyr[0])) },
    // GNSS_LL  (0x98FF1029)
    { 0x98FF1029u, true, false, 100u, 8u,
      "GNSS_LL",
      k_sigs_gnss_ll, static_cast<uint8_t>(sizeof(k_sigs_gnss_ll) / sizeof(k_sigs_gnss_ll[0])) },
    // GNSS_AV  (0x98FF1129)
    { 0x98FF1129u, true, false, 100u, 8u,
      "GNSS_AV",
      k_sigs_gnss_av, static_cast<uint8_t>(sizeof(k_sigs_gnss_av) / sizeof(k_sigs_gnss_av[0])) },
    // WHEELS_1  (0x8CFF202A)
    { 0x8CFF202Au, true, false, 10u, 8u,
      "WHEELS_1",
      k_sigs_wheels_1, static_cast<uint8_t>(sizeof(k_sigs_wheels_1) / sizeof(k_sigs_wheels_1[0])) },
    // STEER_STATE  (0x8CFF212A)
    { 0x8CFF212Au, true, false, 10u, 8u,
      "STEER_STATE",
      k_sigs_steer_state, static_cast<uint8_t>(sizeof(k_sigs_steer_state) / sizeof(k_sigs_steer_state[0])) },
    // BATT_STATE  (0x98FF302B)
    { 0x98FF302Bu, true, false, 50u, 8u,
      "BATT_STATE",
      k_sigs_batt_state, static_cast<uint8_t>(sizeof(k_sigs_batt_state) / sizeof(k_sigs_batt_state[0])) },
    // RADAR_1  (0x98FF402C)
    { 0x98FF402Cu, true, false, 50u, 8u,
      "RADAR_1",
      k_sigs_radar_1, static_cast<uint8_t>(sizeof(k_sigs_radar_1) / sizeof(k_sigs_radar_1[0])) },
    // VEHICLE_STATE_1  (0x98FF50F0)
    { 0x98FF50F0u, true, false, 10u, 8u,
      "VEHICLE_STATE_1",
      k_sigs_vehicle_state_1, static_cast<uint8_t>(sizeof(k_sigs_vehicle_state_1) / sizeof(k_sigs_vehicle_state_1[0])) },
    // MOTOR_STATE_1  (0x98FF51F0)
    { 0x98FF51F0u, true, false, 10u, 8u,
      "MOTOR_STATE_1",
      k_sigs_motor_state_1, static_cast<uint8_t>(sizeof(k_sigs_motor_state_1) / sizeof(k_sigs_motor_state_1[0])) },
    // BRAKE_STATE  (0x98FF52F0)
    { 0x98FF52F0u, true, false, 10u, 8u,
      "BRAKE_STATE",
      k_sigs_brake_state, static_cast<uint8_t>(sizeof(k_sigs_brake_state) / sizeof(k_sigs_brake_state[0])) },
    // POSITION_STATE  (0x98FF53F0)
    { 0x98FF53F0u, true, false, 50u, 8u,
      "POSITION_STATE",
      k_sigs_position_state, static_cast<uint8_t>(sizeof(k_sigs_position_state) / sizeof(k_sigs_position_state[0])) },
    // ORIENTATION_STATE  (0x98FF54F0)
    { 0x98FF54F0u, true, false, 50u, 8u,
      "ORIENTATION_STATE",
      k_sigs_orientation_state, static_cast<uint8_t>(sizeof(k_sigs_orientation_state) / sizeof(k_sigs_orientation_state[0])) },
    // DRIVETRAIN_STATE  (0x98FF55F0)
    { 0x98FF55F0u, true, false, 100u, 8u,
      "DRIVETRAIN_STATE",
      k_sigs_drivetrain_state, static_cast<uint8_t>(sizeof(k_sigs_drivetrain_state) / sizeof(k_sigs_drivetrain_state[0])) },
    // DIAGNOSTIC_STATE  (0x98FF60F0)
    { 0x98FF60F0u, true, false, 100u, 8u,
      "DIAGNOSTIC_STATE",
      k_sigs_diagnostic_state, static_cast<uint8_t>(sizeof(k_sigs_diagnostic_state) / sizeof(k_sigs_diagnostic_state[0])) },
};

static const uint8_t k_frame_count = 16u;
static const uint8_t k_rx_count     = 1u;
static const uint8_t k_tx_count     = 15u;

// ── Lookup helpers ──────────────────────────────────────────────────────

// Linear search is fine for ≤ 16 frames — runs in < 1 µs on M7.
inline const FrameDef* find_frame(uint32_t id) {
    for (uint8_t i = 0; i < k_frame_count; ++i)
        if (k_frames[i].id == id) return &k_frames[i];
    return nullptr;
}

inline const FrameDef* find_rx_frame(uint32_t id) {
    for (uint8_t i = 0; i < k_frame_count; ++i)
        if (k_frames[i].id == id && k_frames[i].is_rx) return &k_frames[i];
    return nullptr;
}

inline const FrameDef* find_tx_frame(uint32_t id) {
    for (uint8_t i = 0; i < k_frame_count; ++i)
        if (k_frames[i].id == id && !k_frames[i].is_rx) return &k_frames[i];
    return nullptr;
}

// Iterate TX frames in definition order.
inline const FrameDef* tx_frame_at(uint8_t idx) {
    uint8_t count = 0;
    for (uint8_t i = 0; i < k_frame_count; ++i) {
        if (!k_frames[i].is_rx) {
            if (count == idx) return &k_frames[i];
            ++count;
        }
    }
    return nullptr;
}

} // namespace can_static
