#!/usr/bin/env bash
# scripts/gen_http_token.sh
# Generates the HTTPS credentials for the Zephyr web server:
#   - A random 32-byte hex Bearer token  → zephyr/src/http/http_auth.hpp
#   - A self-signed RSA-2048 TLS cert    → zephyr/certs/server.crt
#   - The matching private key           → zephyr/certs/server.key
#
# Run once before 'west build'.  Re-run any time you want to rotate credentials.
# All outputs are .gitignored — never commit them.
#
# Usage:
#   bash scripts/gen_http_token.sh
#   west build -b nucleo_h753zi zephyr

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CERT_DIR="$REPO_ROOT/zephyr/certs"
AUTH_HEADER="$REPO_ROOT/zephyr/src/http/http_auth.hpp"

mkdir -p "$CERT_DIR"

# ── Token ──────────────────────────────────────────────────────────────────────
TOKEN=$(openssl rand -hex 32)

cat > "$AUTH_HEADER" <<EOF
// zephyr/src/http/http_auth.hpp
// AUTO-GENERATED by scripts/gen_http_token.sh — do NOT commit.
// Re-run the script to rotate credentials.
#pragma once

// Bearer token required in every HTTP request:
//   Authorization: Bearer <token>
static constexpr char HDV_API_TOKEN[] = "${TOKEN}";
EOF

echo "[token]  Written to: $AUTH_HEADER"
echo "[token]  Value     : $TOKEN"
echo ""
echo "  curl example:"
echo "    curl -k -H 'Authorization: Bearer ${TOKEN}' https://192.168.1.80/"
echo ""

# ── TLS certificate + private key ──────────────────────────────────────────────
# Delegate to gen_tls_certs.sh so the IP SAN is always set correctly.
bash "$(dirname "$0")/gen_tls_certs.sh"

echo "All done — rebuild and reflash firmware to deploy new credentials."
