#!/usr/bin/env bash
# gen_wifi_creds.sh — write Wi-Fi SSID and password to the gitignored
# zephyr/wifi_creds.conf file consumed by CMakeLists.txt (EXTRA_CONF_FILE).
#
# Usage:
#   bash scripts/gen_wifi_creds.sh
#
# The file is gitignored and never committed — same pattern as http_auth.hpp.

set -euo pipefail

OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/zephyr/wifi_creds.conf"

read -rp "Wi-Fi SSID     : " SSID
read -rsp "Wi-Fi password : " PASS
echo

if [[ -z "${SSID}" ]]; then
    echo "Error: SSID cannot be empty" >&2
    exit 1
fi

cat > "${OUT}" <<EOF
# Wi-Fi credentials — gitignored, generated by scripts/gen_wifi_creds.sh
# Re-run to change SSID or password.
CONFIG_ST67W61_SSID="${SSID}"
CONFIG_ST67W61_PASSWORD="${PASS}"
EOF

echo "Written: ${OUT}"
echo "  SSID    : ${SSID}"
echo "  Password: (hidden)"
