#!/usr/bin/env python3
"""
tools/gen_can_map.py
Parse config/can_map.dbc and emit zephyr/src/can/can_map_static.hpp —
a zero-allocation, constexpr CAN map baked into MCU flash.

Usage (from repo root):
    python3 tools/gen_can_map.py

Output:
    zephyr/src/can/can_map_static.hpp
"""

import re
import sys
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Optional

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).parent.parent
DBC_PATH  = REPO_ROOT / "config" / "can_map.dbc"
OUT_PATH  = REPO_ROOT / "zephyr" / "src" / "can" / "can_map_static.hpp"

# ── Data classes ──────────────────────────────────────────────────────────────

@dataclass
class Signal:
    name:       str
    start_bit:  int
    bit_len:    int
    little_end: bool   # True = Intel (@1), False = Motorola (@0)
    is_signed:  bool
    factor:     float
    offset:     float
    min_val:    float
    max_val:    float
    unit:       str    = ""

@dataclass
class Frame:
    raw_id:   int          # decimal from DBC
    name:     str
    dlc:      int
    signals:  List[Signal] = field(default_factory=list)
    dir:      str          = "tx"   # "rx" or "tx"
    cycle_ms: int          = 0

# ── DBC parser ────────────────────────────────────────────────────────────────

# SG_ name : start|len@endian+/- (factor,offset) [min|max] "unit" receivers
SIG_RE = re.compile(
    r'SG_\s+(\w+)\s*:\s*(\d+)\|(\d+)@([01])([+-])\s*'
    r'\(([^,]+),([^)]+)\)\s*\[([^|]+)\|([^\]]+)\]\s*"([^"]*)"'
)

def parse_dbc(path: Path) -> List[Frame]:
    text = path.read_text()
    frames: List[Frame] = []
    cur: Optional[Frame] = None

    for line in text.splitlines():
        line = line.strip()

        # ── BO_ message header ────────────────────────────────────────────────
        m = re.match(r'BO_\s+(\d+)\s+(\w+)\s*:\s*(\d+)', line)
        if m:
            cur = Frame(raw_id=int(m.group(1)),
                        name=m.group(2),
                        dlc=int(m.group(3)))
            frames.append(cur)
            continue

        # ── SG_ signal ────────────────────────────────────────────────────────
        m = SIG_RE.search(line)
        if m and cur:
            cur.signals.append(Signal(
                name       = m.group(1),
                start_bit  = int(m.group(2)),
                bit_len    = int(m.group(3)),
                little_end = (m.group(4) == '1'),
                is_signed  = (m.group(5) == '-'),
                factor     = float(m.group(6)),
                offset     = float(m.group(7)),
                min_val    = float(m.group(8)),
                max_val    = float(m.group(9)),
                unit       = m.group(10),
            ))
            continue

    # ── Direction attributes ───────────────────────────────────────────────────
    # BA_ "Direction" BO_ <id> "rx"|"tx" ;
    for m in re.finditer(r'BA_\s+"Direction"\s+BO_\s+(\d+)\s+"(\w+)"', text):
        raw_id = int(m.group(1))
        direction = m.group(2)
        for f in frames:
            if f.raw_id == raw_id:
                f.dir = direction

    # ── Cycle time attributes ─────────────────────────────────────────────────
    # BA_ "GenMsgCycleTime" BO_ <id> <ms> ;
    for m in re.finditer(r'BA_\s+"GenMsgCycleTime"\s+BO_\s+(\d+)\s+(\d+)', text):
        raw_id   = int(m.group(1))
        cycle_ms = int(m.group(2))
        for f in frames:
            if f.raw_id == raw_id:
                f.cycle_ms = cycle_ms

    return frames

# ── Code generator ────────────────────────────────────────────────────────────

def c_float(v: float) -> str:
    """Format float for C constexpr — always include decimal point."""
    if v == 0.0:
        return "0.0f"
    s = f"{v:.10g}"
    # Ensure there's a decimal point so compilers don't warn (e.g. 1f → 1.0f)
    if '.' not in s and 'e' not in s and 'E' not in s:
        s += ".0"
    return s + "f"

def safe_ident(name: str) -> str:
    """Convert frame/signal name to a valid C identifier (lower-case)."""
    return re.sub(r'[^0-9a-zA-Z_]', '_', name).lower()

def generate(frames: List[Frame]) -> str:
    rx = [f for f in frames if f.dir == "rx"]
    tx = [f for f in frames if f.dir == "tx"]

    lines = []
    def emit(*args):
        lines.append(" ".join(str(a) for a in args))

    emit("// AUTO-GENERATED by tools/gen_can_map.py — DO NOT EDIT MANUALLY")
    emit("// Source: config/can_map.dbc")
    emit("// Re-generate: python3 tools/gen_can_map.py")
    emit("//")
    emit(f"// {len(rx)} RX frame(s), {len(tx)} TX frame(s), "
         f"{sum(len(f.signals) for f in frames)} signals total")
    emit("#pragma once")
    emit("#include <stdint.h>")
    emit("#include <stdbool.h>")
    emit()
    emit("namespace can_static {")
    emit()

    # ── Structs ───────────────────────────────────────────────────────────────
    emit("// Signal descriptor — all data lives in flash (constexpr/const).")
    emit("struct SigDef {")
    emit("    const char* name;")
    emit("    int16_t     start_bit;")
    emit("    uint8_t     bit_len;")
    emit("    bool        little_endian;  // true=Intel (@1), false=Motorola (@0)")
    emit("    bool        is_signed;")
    emit("    float       factor;")
    emit("    float       offset;")
    emit("};")
    emit()
    emit("// Frame descriptor.")
    emit("struct FrameDef {")
    emit("    uint32_t        id;          // 29-bit J1939 identifier (no EFF flag)")
    emit("    bool            is_extended; // always true for J1939")
    emit("    bool            is_rx;       // true = we receive this frame")
    emit("    uint16_t        cycle_ms;    // nominal TX period (0 = event-driven)")
    emit("    uint8_t         dlc;")
    emit("    const char*     name;")
    emit("    const SigDef*   sigs;")
    emit("    uint8_t         sig_count;")
    emit("};")
    emit()

    # ── Per-frame signal arrays ───────────────────────────────────────────────
    emit("// ── Signal arrays (one per frame, stored in flash) " + "─" * 37)
    emit()
    for f in frames:
        ident = safe_ident(f.name)
        emit(f"static const SigDef k_sigs_{ident}[] = {{")
        for s in f.signals:
            le  = "true" if s.little_end else "false"
            sgn = "true" if s.is_signed  else "false"
            emit(f"    {{ \"{s.name}\", {s.start_bit}, {s.bit_len}, "
                 f"{le}, {sgn}, {c_float(s.factor)}, {c_float(s.offset)} }},")
        emit("};")
        emit()

    # ── Frame table ───────────────────────────────────────────────────────────
    total = len(frames)
    emit("// ── Frame table " + "─" * 57)
    emit()
    emit(f"static const FrameDef k_frames[{total}] = {{")
    for f in frames:
        ident = safe_ident(f.name)
        is_rx = "true" if f.dir == "rx" else "false"
        emit(f"    // {f.name}  (0x{f.raw_id:08X})")
        emit(f"    {{ 0x{f.raw_id:08X}u, true, {is_rx}, "
             f"{f.cycle_ms}u, {f.dlc}u,")
        emit(f"      \"{f.name}\",")
        emit(f"      k_sigs_{ident}, "
             f"static_cast<uint8_t>(sizeof(k_sigs_{ident}) / sizeof(k_sigs_{ident}[0])) }},")
    emit("};")
    emit()
    emit(f"static const uint8_t k_frame_count = {total}u;")
    emit(f"static const uint8_t k_rx_count     = {len(rx)}u;")
    emit(f"static const uint8_t k_tx_count     = {len(tx)}u;")
    emit()

    # ── Lookup helpers (inline, no heap) ─────────────────────────────────────
    emit("// ── Lookup helpers " + "─" * 54)
    emit()
    emit("// Linear search is fine for ≤ 16 frames — runs in < 1 µs on M7.")
    emit("inline const FrameDef* find_frame(uint32_t id) {")
    emit("    for (uint8_t i = 0; i < k_frame_count; ++i)")
    emit("        if (k_frames[i].id == id) return &k_frames[i];")
    emit("    return nullptr;")
    emit("}")
    emit()
    emit("inline const FrameDef* find_rx_frame(uint32_t id) {")
    emit("    for (uint8_t i = 0; i < k_frame_count; ++i)")
    emit("        if (k_frames[i].id == id && k_frames[i].is_rx) return &k_frames[i];")
    emit("    return nullptr;")
    emit("}")
    emit()
    emit("inline const FrameDef* find_tx_frame(uint32_t id) {")
    emit("    for (uint8_t i = 0; i < k_frame_count; ++i)")
    emit("        if (k_frames[i].id == id && !k_frames[i].is_rx) return &k_frames[i];")
    emit("    return nullptr;")
    emit("}")
    emit()
    emit("// Iterate TX frames in definition order.")
    emit("inline const FrameDef* tx_frame_at(uint8_t idx) {")
    emit("    uint8_t count = 0;")
    emit("    for (uint8_t i = 0; i < k_frame_count; ++i) {")
    emit("        if (!k_frames[i].is_rx) {")
    emit("            if (count == idx) return &k_frames[i];")
    emit("            ++count;")
    emit("        }")
    emit("    }")
    emit("    return nullptr;")
    emit("}")
    emit()
    emit("} // namespace can_static")

    return "\n".join(lines) + "\n"

# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    if not DBC_PATH.exists():
        print(f"ERROR: DBC not found: {DBC_PATH}", file=sys.stderr)
        sys.exit(1)

    frames = parse_dbc(DBC_PATH)
    print(f"Parsed {len(frames)} frames, "
          f"{sum(len(f.signals) for f in frames)} signals")
    for f in frames:
        print(f"  [{f.dir:2s}] 0x{f.raw_id:08X}  {f.name:<28s}  "
              f"{len(f.signals)} sigs  {f.cycle_ms} ms")

    code = generate(frames)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(code)
    print(f"\nWrote {OUT_PATH.relative_to(REPO_ROOT)}")
    print(f"  {len(code)} bytes, {code.count(chr(10))} lines")

if __name__ == "__main__":
    main()
